fx_version 'cerulean'
game 'gta5'

lua54 'yes'

name 'esx_policejob'
author 'DK-Script (generated by Cursor agent)'
description 'ESX Legacy/New ESX police job (basic)'
version '1.0.0'

shared_scripts {
  '@es_extended/imports.lua',
  'shared/config.lua',
  'shared/locales/en.lua',
  'shared/locales/hu.lua',
}

client_scripts {
  'client/main.lua',
}

server_scripts {
  'server/main.lua',
}

dependencies {
  'es_extended',
  'esx_society',
  'esx_addoninventory',
  'esx_datastore',
  'esx_billing',
}
